version: '3'

services:
  nginx:
    build: ./nginx
    links:
      - app1:app1
      - app2:app2
    ports:
      - '3000:3000'
    volumes:
      - /etc/nginx/psw:/etc/nginx/psw
      - /etc/nginx/ssl:/etc/nginx/ssl
    environment:
      - DOMAIN_NAME=gotoro.com
  app1:
    build: .
    links:
      - redis
    ports:
      - '5000'
    volumes:
      - /tmp:/tmp
    environment:
      - MODE=prod
      - CLOUDWATCH_REGION=us-west-2
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14

    env_file:
      - .env

    volumes:
      - .:/gotoro.com-api:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql/data
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_DB: maixepdb

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mysql-data:
