version: 2.1
jobs:
  build:
    working_directory: ~/hello-sts
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: ssh -p 3000 root@103.90.226.237 "cd ../gotoro.com-api; git pull; pm2 start gotoro.com-api";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build